# Generated by Django 4.1.2 on 2023-01-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior1', models.CharField(max_length=255)),
                ('behavior1_details', models.CharField(default='', max_length=1000)),
                ('behavior1_intensity', models.IntegerField()),
                ('behavior1_frequency', models.IntegerField()),
                ('behavior2', models.CharField(max_length=255)),
                ('behavior2_details', models.CharField(default='', max_length=1000)),
                ('behavior2_intensity', models.IntegerField()),
                ('behavior2_frequency', models.IntegerField()),
                ('behavior3', models.CharField(max_length=255)),
                ('behavior3_details', models.CharField(default='', max_length=1000)),
                ('behavior3_intensity', models.IntegerField()),
                ('behavior3_frequency', models.IntegerField()),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('behaviors', models.ManyToManyField(related_name='child_behaviors', to='specialist.behavior')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.child')),
            ],
        ),
    ]
