# Generated by Django 4.1.5 on 2023-02-03 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=255)),
                ('behavior_details', models.CharField(default='', max_length=1000)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.child')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('scared', 'Scared'), ('tired', 'Tired'), ('confused', 'Confused'), ('disappointed', 'Disappointed'), ('frustrated', 'Frustrated'), ('lonely', 'Lonely'), ('nervous', 'Nervous'), ('proud', 'Proud'), ('surprised', 'Surprised'), ('worried', 'Worried'), ('overwhelmed', 'Overwhelmed')], max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField(max_length=3000)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.child')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_intensity', models.IntegerField(null=True)),
                ('behavior_frequency', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.behavior')),
            ],
        ),
        migrations.AddField(
            model_name='behavior',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.child'),
        ),
    ]
