# Generated by Django 4.1.2 on 2023-01-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='behaviors',
        ),
        migrations.AddField(
            model_name='behavior',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='specialist.child'),
            preserve_default=False,
        ),
    ]
