# Generated by Django 4.1.2 on 2023-01-30 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_remove_child_behaviors_behavior_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='behavior1_frequency',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior1_intensity',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior2_frequency',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior2_intensity',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior3_frequency',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior3_intensity',
        ),
        migrations.CreateModel(
            name='BehaviorCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior1_intensity', models.IntegerField()),
                ('behavior1_frequency', models.IntegerField()),
                ('behavior2_intensity', models.IntegerField()),
                ('behavior2_frequency', models.IntegerField()),
                ('behavior3_intensity', models.IntegerField()),
                ('behavior3_frequency', models.IntegerField()),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.behavior')),
            ],
        ),
    ]
