# Generated by Django 4.1.5 on 2023-02-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0003_alter_child_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={},
        ),
    ]
