# Generated by Django 4.1.2 on 2023-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0003_remove_behavior_behavior1_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorcheckin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
