# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0003_behavior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AddField(
            model_name='behavior',
            name='behavior1_details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='behavior',
            name='behavior2_details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='behavior',
            name='behavior3_details',
            field=models.CharField(default='', max_length=1000),
        ),
      
    ]
