# Generated by Django 4.1.5 on 2023-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_alter_child_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorcheckin',
            name='note',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
