# Generated by Django 4.1.2 on 2023-01-31 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_behaviorcheckin_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('scared', 'Scared'), ('tired', 'Tired'), ('confused', 'Confused'), ('disappointed', 'Disappointed'), ('frustrated', 'Frustrated'), ('lonely', 'Lonely'), ('nervous', 'Nervous'), ('proud', 'Proud'), ('surprised', 'Surprised'), ('worried', 'Worried'), ('overwhelmed', 'Overwhelmed')], max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.child')),
            ],
        ),
    ]
