# Generated by Django 4.1.2 on 2023-02-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='note',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
