# Generated by Django 4.1.6 on 2023-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_behaviorcheckin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='note',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
