# Generated by Django 4.1.2 on 2023-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0006_feeling_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='note',
            field=models.TextField(max_length=3000),
        ),
    ]
