# Generated by Django 4.1.5 on 2023-01-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0007_alter_child_parent'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE specialist_child DROP COLUMN parent_id;")
    ]
