# Generated by Django 4.1.2 on 2023-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0007_alter_feeling_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='feeling',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('scared', 'Scared'), ('tired', 'Tired'), ('confused', 'Confused'), ('disappointed', 'Disappointed'), ('frustrated', 'Frustrated'), ('lonely', 'Lonely'), ('nervous', 'Nervous'), ('proud', 'Proud'), ('surprised', 'Surprised'), ('worried', 'Worried'), ('overwhelmed', 'Overwhelmed')], max_length=20),
        ),
    ]
