# Generated by Django 4.1.5 on 2023-01-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0008_auto_20230126_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
    ]
