# Generated by Django 4.1.2 on 2023-02-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0009_alter_feeling_feeling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behavior',
            old_name='behavior1',
            new_name='target_behavior',
        ),
        migrations.RenameField(
            model_name='behavior',
            old_name='behavior1_details',
            new_name='target_behavior_details',
        ),
        migrations.RenameField(
            model_name='behaviorcheckin',
            old_name='behavior1_frequency',
            new_name='behavior_frequency',
        ),
        migrations.RenameField(
            model_name='behaviorcheckin',
            old_name='behavior1_intensity',
            new_name='behavior_intensity',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior2',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior2_details',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior3',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='behavior3_details',
        ),
        migrations.RemoveField(
            model_name='behaviorcheckin',
            name='behavior2_frequency',
        ),
        migrations.RemoveField(
            model_name='behaviorcheckin',
            name='behavior2_intensity',
        ),
        migrations.RemoveField(
            model_name='behaviorcheckin',
            name='behavior3_frequency',
        ),
        migrations.RemoveField(
            model_name='behaviorcheckin',
            name='behavior3_intensity',
        ),
    ]
