# Generated by Django 4.1.2 on 2023-02-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0012_rename_target_behavior_behavior_behavior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorcheckin',
            name='behavior_frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='behaviorcheckin',
            name='behavior_intensity',
            field=models.IntegerField(null=True),
        ),
    ]
